const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const data=fs.readFileSync('literacy/data-v2.js','utf8'),app=fs.readFileSync('literacy/app.js','utf8');
const content={window:{}};vm.runInNewContext(data,content);const lessons=content.window.LITERACY_V2;
assert.equal(lessons.length,24);assert.equal(lessons.reduce((n,l)=>n+l.questions.length,0),84);
for(const l of lessons){assert.equal(l.questions.length,l.session==='A'?3:4);assert(l.passage.length>=(l.session==='A'?2:3));for(const q of l.questions){assert(q.answer>=0&&q.answer<q.options.length);assert(q.refs.every(n=>n>=1&&n<=l.passage.length+(l.table?1:0)));assert(q.hint&&q.evidence);}}
const KEY='heeyoon-literacy-board:v2',storage=new Map([['heeyoon-literacy-board:v1','legacy-sentinel'],['heeyoon-today-board:v1','main-sentinel']]);
function launch(){const nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,{style:{},classList:{add(){}},querySelectorAll(){return[]},scrollIntoView(){},focus(){},innerHTML:''});return nodes.get(id);};const context={window:content.window,document:{getElementById:get,querySelectorAll(){return[]}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},Date};vm.runInNewContext(app.replace('render();\n})();','globalThis.test={qs,lessons,setActive(){active=true;},render,renderStudy,state};render();\n})();'),context);return {context,get,test:context.test};}
let h=launch();assert(!storage.has(KEY),'preview must not save');for(const l of lessons){h.test.renderStudy(l);const html=h.get('study').innerHTML;assert(html.includes('이 회차에서 연습할 읽기 기술'));assert(!html.includes('data-answer'));for(const q of l.questions)assert(!html.includes(q.q));}h.test.setActive();h.test.render();h.get('next').onclick();assert(h.get('study').innerHTML.includes(lessons[0].questions[0].q),'unresolved question cannot be skipped');let s=h.test.qs(lessons[0],0);
function submit(choice){s.final=choice;s.confidence='sure';s.evidence=[2];h.test.render();h.get('check').onclick();}
submit(1);assert.equal(s.first,1);assert.equal(s.attempts.length,1);assert(!s.resolved&&!s.hintUsed);assert(!h.get('study').innerHTML.includes('정답:'));
submit(2);assert.equal(s.attempts.length,2);assert(!s.resolved);h.get('hint').onclick();assert(s.hintUsed);h.get('reveal').onclick();assert(s.revealed&&!s.resolved);h.get('understood').onclick();assert.equal(s.result,'blue');assert.equal(s.final,0);
h=launch();s=h.test.qs(lessons[0],0);assert(s.resolved&&s.hintUsed);assert.equal(s.first,1);assert.equal(s.firstConfidence,'sure');
assert.equal(storage.get('heeyoon-literacy-board:v1'),'legacy-sentinel');assert.equal(storage.get('heeyoon-today-board:v1'),'main-sentinel');
h.test.setActive();s=h.test.qs(lessons[0],1);s.final=1;s.confidence='unsure';s.evidence=[3];
// Main schedule loader: run the real initialization functions with each stored setting.
const main=fs.readFileSync('index.html','utf8').match(/<script>\(\(\)=>\{([\s\S]*)\}\)\(\);<\/script>/)[1];
const prefix=main.slice(0,main.indexOf('function renderToday'));
for(const days of [undefined,[4],[1,5],[]]){const saved=days===undefined?null:{version:1,settings:{bookGoal:3,taskDays:{literacy:days}},days:{'2026-01-01':{tasks:{reading:{bookTitle:'보존',doneAt:'x'}}}}};const ctx={localStorage:{getItem:()=>JSON.stringify(saved)}};vm.runInNewContext(prefix+';globalThis.result=state;',ctx);assert.deepEqual(Array.from(ctx.result.settings.taskDays.literacy),days??[2,4]);if(saved)assert.equal(ctx.result.days['2026-01-01'].tasks.reading.bookTitle,'보존');}
assert(main.includes('학습 내용 미리보기'));new vm.Script(app);new vm.Script(data);
// Render and solve every session, including table evidence and completed records.
for(const l of lessons){const bag=new Map();const get=id=>{if(!bag.has(id))bag.set(id,{style:{},classList:{add(){}},querySelectorAll(){return[]},focus(){},innerHTML:''});return bag.get(id);};const ctx={window:content.window,document:{getElementById:get,querySelectorAll(){return[]}},localStorage:{getItem:()=>null,setItem(){}},Date};vm.runInNewContext(app.replace('render();\n})();','globalThis.test={set(i,id){current=id;active=true;question=i;render();return qs(lessons.find(l=>l.id===id),i);},state};render();\n})();'),ctx);for(let i=0;i<l.questions.length;i++){const s=ctx.test.set(i,l.id),q=l.questions[i];s.final=q.answer;s.confidence='sure';s.evidence=[...q.refs];get('check').onclick();assert.equal(s.result,'green');assert(s.evidenceCorrect);}get('finish').onclick();assert(ctx.test.state.sessions[l.id].completedAt);assert.equal(ctx.test.state.sessions[l.id].result,'green');}
console.log('PASS: 24 sessions / 84 questions, all session completion, references, retry → hint → explanation → acknowledgement, reload, legacy key protection, new/custom/empty schedules.');
