(() => {
  'use strict';
  const KEY='heeyoon-english-board:v2',DATA=window.ENGLISH_V2_WEEK1,now=()=>new Date().toISOString();
  let state;try{state=JSON.parse(localStorage.getItem(KEY))||{version:1,week:1,sessions:{}}}catch{state={version:1,week:1,sessions:{}}}
  let section='A',index=0,active=false;
  const $=id=>document.getElementById(id),save=()=>localStorage.setItem(KEY,JSON.stringify(state)),session=()=>state.sessions[section]||= {items:{},completedAt:null};
  function item(){return session().items[index]||=(section==='C'?{spoken:false,helpUsed:false,feeling:null,choice:null}:{choice:null,firstCorrect:null,attempts:[],hintUsed:false,relistenCount:0,resolved:false})}
  function speak(text){if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.lang='en-US';speechSynthesis.speak(u)}
  function render(){const l=DATA[section];$('sections').className='tabs';$('sections').innerHTML=Object.entries(DATA).map(([id,x])=>`<button class="tab ${id===section?'active':''}" data-section="${id}">${x.icon} ${id} ${x.title}</button>`).join('');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;index=0;active=false;render()});const root=$('study'),r=session();if(!active){root.innerHTML=`<span class="eyebrow">${l.icon} ${section} · ${Object.keys(r.items).length? '진행 중':'시작 전'}</span><h2>${l.title} 👀</h2><p class="quiet">한 번에 하나씩 만나봐요.</p><button class="btn primary" data-action="begin">${r.completedAt?'완료 기록 보기':'시작하기'}</button>`;document.querySelector('[data-action="begin"]').onclick=()=>{active=true;index=0;render()};return}if(r.completedAt){root.innerHTML='<h2>🎉 1주차 완료!</h2><p>작은 가게 탐험을 잘 마쳤어요.</p>';return}const q=l.items[index],s=item(),choices=q.choices||q.options||[];root.innerHTML=`<span class="eyebrow">${l.icon} ${section} · ${index+1}/${l.items.length}</span><h2>${q.prompt}</h2><div class="english${section==='B'&&!s.relistenCount?' awaiting-listen':''}" lang="en">${section==='B'&&!s.relistenCount?'🔊 듣기를 먼저 눌러보세요':q.text.includes('{choice}')?q.text.replace('{choice}',s.choice||'____'):q.text}</div>${section==='A'?'<button class="btn" data-action="speak">🔊 듣기</button>':''}${section==='B'?'<button class="btn" data-action="listen">🔊 듣기</button><button class="btn" data-action="relisten">다시 듣기</button>':''}${choices.length?`<div class="options">${choices.map((x,i)=>{const label=Array.isArray(x)?x[0]:x;const value=Array.isArray(x)?x[1]:i;return `<button class="option" data-choice="${value}" aria-pressed="${String(s.choice)===String(value)}">${label}</button>`}).join('')}</div>`:''}<div class="feedback">${s.hintUsed?'🔎 '+q.hint:s.attempts?.length?'한 번 더 볼까요?':''}</div><div class="actions">${section==='C'?`<button class="btn" data-action="help">도움 필요</button><button class="btn primary" data-action="spoken" ${q.choices&&!s.choice?'disabled':''}>말해봤어요</button>`:`<button class="btn" data-action="hint" ${s.attempts?.length?'':'disabled'}>힌트</button><button class="btn primary" data-action="check" ${s.choice===null||section==='B'&&!s.relistenCount?'disabled':''}>확인</button>`}</div>`;bind(q,s)}
  function bind(q,s){document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{s.choice=s.choice===b.dataset.choice?null:b.dataset.choice;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action,q,s));}
  function act(a,q,s){if(a==='begin'){active=true;render();return}if(a==='speak'||a==='listen'){s.relistenCount=(s.relistenCount||0)+1;speak(q.text);save();render();return}if(a==='relisten'){s.relistenCount=(s.relistenCount||0)+1;speak(q.text);save();render();return}if(a==='hint'){s.hintUsed=true;save();render();return}if(a==='help'){s.helpUsed=true;save();render();return}if(a==='spoken'){s.spoken=true;s.completedAt=now();next();return}if(a==='check'){const correct=String(s.choice)===String(q.answer);if(!s.attempts.length)s.firstCorrect=correct;s.attempts.push({choice:s.choice,correct,at:now()});if(correct){s.resolved=true;next()}else{s.choice=null;save();render()}}}
  function next(){if(index===DATA[section].items.length-1){session().completedAt=now();save();active=false;render()}else{index++;save();render()}}
  render();
})();
